[package]
name = "amqp-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
lapin = "2.5.0"
thiserror = "1.0.63"
tokio = "1.39.2"
tokio-stream = "0.1.15"
tower = "0.4.13"
tracing = "0.1.40"
